# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Image CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build The Docker Image
      run: docker build -t todo-app .

    - name: Run image
      run: docker run -it --name todo-app todo-app
      
    - name: Tag image
      run:  docker tag todo-app:latest iamanh/todo-app:latest               
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/todo-app:latest
